export const allCountries = [
    { name: 'Afghanistan (‫افغانستان‬‎)', abbrev: 'af', dialCode: '93' },
    { name: 'Albania (Shqipëri)', abbrev: 'al', dialCode: '355' },
    { name: 'Algeria (‫الجزائر‬‎)', abbrev: 'dz', dialCode: '213' },
    { name: 'American Samoa', abbrev: 'as', dialCode: '1' },
    { name: 'Andorra', abbrev: 'ad', dialCode: '376' },
    { name: 'Angola', abbrev: 'ao', dialCode: '244' },
    { name: 'Anguilla', abbrev: 'ai', dialCode: '1' },
    { name: 'Antigua and Barbuda', abbrev: 'ag', dialCode: '1' },
    { name: 'Argentina', abbrev: 'ar', dialCode: '54' },
    { name: 'Armenia (Հայաստան)', abbrev: 'am', dialCode: '374' },
    { name: 'Aruba', abbrev: 'aw', dialCode: '297' },
    { name: 'Ascension Island', abbrev: 'ac', dialCode: '247' },
    { name: 'Australia', abbrev: 'au', dialCode: '61' },
    { name: 'Austria (Österreich)', abbrev: 'at', dialCode: '43' },
    { name: 'Azerbaijan (Azərbaycan)', abbrev: 'az', dialCode: '994' },
    { name: 'Bahamas', abbrev: 'bs', dialCode: '1' },
    { name: 'Bahrain (‫البحرين‬‎)', abbrev: 'bh', dialCode: '973' },
    { name: 'Bangladesh (বাংলাদেশ)', abbrev: 'bd', dialCode: '880' },
    { name: 'Barbados', abbrev: 'bb', dialCode: '1' },
    { name: 'Belarus (Беларусь)', abbrev: 'by', dialCode: '375' },
    { name: 'Belgium (België)', abbrev: 'be', dialCode: '32' },
    { name: 'Belize', abbrev: 'bz', dialCode: '501' },
    { name: 'Benin (Bénin)', abbrev: 'bj', dialCode: '229' },
    { name: 'Bermuda', abbrev: 'bm', dialCode: '1' },
    { name: 'Bhutan (འབྲུག)', abbrev: 'bt', dialCode: '975' },
    { name: 'Bolivia', abbrev: 'bo', dialCode: '591' },
    {
        name: 'Bosnia and Herzegovina (Босна и Херцеговина)',
        abbrev: 'ba',
        dialCode: '387',
    },
    { name: 'Botswana', abbrev: 'bw', dialCode: '267' },
    { name: 'Brazil (Brasil)', abbrev: 'br', dialCode: '55' },
    {
        name: 'British Indian Ocean Territory',
        abbrev: 'io',
        dialCode: '246',
    },
    { name: 'British Virgin Islands', abbrev: 'vg', dialCode: '1' },
    { name: 'Brunei', abbrev: 'bn', dialCode: '673' },
    { name: 'Bulgaria (България)', abbrev: 'bg', dialCode: '359' },
    { name: 'Burkina Faso', abbrev: 'bf', dialCode: '226' },
    { name: 'Burundi (Uburundi)', abbrev: 'bi', dialCode: '257' },
    { name: 'Cambodia (កម្ពុជា)', abbrev: 'kh', dialCode: '855' },
    { name: 'Cameroon (Cameroun)', abbrev: 'cm', dialCode: '237' },
    { name: 'Canada', abbrev: 'ca', dialCode: '1' },
    { name: 'Cape Verde (Kabu Verdi)', abbrev: 'cv', dialCode: '238' },
    { name: 'Caribbean Netherlands', abbrev: 'bq', dialCode: '599' },
    { name: 'Cayman Islands', abbrev: 'ky', dialCode: '1' },
    {
        name: 'Central African Republic (République centrafricaine)',
        abbrev: 'cf',
        dialCode: '236',
    },
    { name: 'Chad (Tchad)', abbrev: 'td', dialCode: '235' },
    { name: 'Chile', abbrev: 'cl', dialCode: '56' },
    { name: 'China (中国)', abbrev: 'cn', dialCode: '86' },
    { name: 'Christmas Island', abbrev: 'cx', dialCode: '61' },
    { name: 'Cocos (Keeling) Islands', abbrev: 'cc', dialCode: '61' },
    { name: 'Colombia', abbrev: 'co', dialCode: '57' },
    { name: 'Comoros (‫جزر القمر‬‎)', abbrev: 'km', dialCode: '269' },
    {
        name: 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)',
        abbrev: 'cd',
        dialCode: '243',
    },
    {
        name: 'Congo (Republic) (Congo-Brazzaville)',
        abbrev: 'cg',
        dialCode: '242',
    },
    { name: 'Cook Islands', abbrev: 'ck', dialCode: '682' },
    { name: 'Costa Rica', abbrev: 'cr', dialCode: '506' },
    { name: 'Côte d’Ivoire', abbrev: 'ci', dialCode: '225' },
    { name: 'Croatia (Hrvatska)', abbrev: 'hr', dialCode: '385' },
    { name: 'Cuba', abbrev: 'cu', dialCode: '53' },
    { name: 'Curaçao', abbrev: 'cw', dialCode: '599' },
    { name: 'Cyprus (Κύπρος)', abbrev: 'cy', dialCode: '357' },
    {
        name: 'Czech Republic (Česká republika)',
        abbrev: 'cz',
        dialCode: '420',
    },
    { name: 'Denmark (Danmark)', abbrev: 'dk', dialCode: '45' },
    { name: 'Djibouti', abbrev: 'dj', dialCode: '253' },
    { name: 'Dominica', abbrev: 'dm', dialCode: '1' },
    {
        name: 'Dominican Republic (República Dominicana)',
        abbrev: 'do',
        dialCode: '1',
    },
    { name: 'Ecuador', abbrev: 'ec', dialCode: '593' },
    { name: 'Egypt (‫مصر‬‎)', abbrev: 'eg', dialCode: '20' },
    { name: 'El Salvador', abbrev: 'sv', dialCode: '503' },
    {
        name: 'Equatorial Guinea (Guinea Ecuatorial)',
        abbrev: 'gq',
        dialCode: '240',
    },
    { name: 'Eritrea', abbrev: 'er', dialCode: '291' },
    { name: 'Estonia (Eesti)', abbrev: 'ee', dialCode: '372' },
    { name: 'Eswatini', abbrev: 'sz', dialCode: '268' },
    { name: 'Ethiopia', abbrev: 'et', dialCode: '251' },
    {
        name: 'Falkland Islands (Islas Malvinas)',
        abbrev: 'fk',
        dialCode: '500',
    },
    { name: 'Faroe Islands (Føroyar)', abbrev: 'fo', dialCode: '298' },
    { name: 'Fiji', abbrev: 'fj', dialCode: '679' },
    { name: 'Finland (Suomi)', abbrev: 'fi', dialCode: '358' },
    { name: 'France', abbrev: 'fr', dialCode: '33' },
    {
        name: 'French Guiana (Guyane française)',
        abbrev: 'gf',
        dialCode: '594',
    },
    {
        name: 'French Polynesia (Polynésie française)',
        abbrev: 'pf',
        dialCode: '689',
    },
    { name: 'Gabon', abbrev: 'ga', dialCode: '241' },
    { name: 'Gambia', abbrev: 'gm', dialCode: '220' },
    { name: 'Georgia (საქართველო)', abbrev: 'ge', dialCode: '995' },
    { name: 'Germany (Deutschland)', abbrev: 'de', dialCode: '49' },
    { name: 'Ghana (Gaana)', abbrev: 'gh', dialCode: '233' },
    { name: 'Gibraltar', abbrev: 'gi', dialCode: '350' },
    { name: 'Greece (Ελλάδα)', abbrev: 'gr', dialCode: '30' },
    { name: 'Greenland (Kalaallit Nunaat)', abbrev: 'gl', dialCode: '299' },
    { name: 'Grenada', abbrev: 'gd', dialCode: '1' },
    { name: 'Guadeloupe', abbrev: 'gp', dialCode: '590' },
    { name: 'Guam', abbrev: 'gu', dialCode: '1' },
    { name: 'Guatemala', abbrev: 'gt', dialCode: '502' },
    { name: 'Guernsey', abbrev: 'gg', dialCode: '44' },
    { name: 'Guinea (Guinée)', abbrev: 'gn', dialCode: '224' },
    { name: 'Guinea-Bissau (Guiné Bissau)', abbrev: 'gw', dialCode: '245' },
    { name: 'Guyana', abbrev: 'gy', dialCode: '592' },
    { name: 'Haiti', abbrev: 'ht', dialCode: '509' },
    { name: 'Honduras', abbrev: 'hn', dialCode: '504' },
    { name: 'Hong Kong (香港)', abbrev: 'hk', dialCode: '852' },
    { name: 'Hungary (Magyarország)', abbrev: 'hu', dialCode: '36' },
    { name: 'Iceland (Ísland)', abbrev: 'is', dialCode: '354' },
    { name: 'India (भारत)', abbrev: 'in', dialCode: '91' },
    { name: 'Indonesia', abbrev: 'id', dialCode: '62' },
    { name: 'Iran (‫ایران‬‎)', abbrev: 'ir', dialCode: '98' },
    { name: 'Iraq (‫العراق‬‎)', abbrev: 'iq', dialCode: '964' },
    { name: 'Ireland', abbrev: 'ie', dialCode: '353' },
    { name: 'Isle of Man', abbrev: 'im', dialCode: '44' },
    { name: 'Israel (‫ישראל‬‎)', abbrev: 'il', dialCode: '972' },
    { name: 'Italy (Italia)', abbrev: 'it', dialCode: '39' },
    { name: 'Jamaica', abbrev: 'jm', dialCode: '1' },
    { name: 'Japan (日本)', abbrev: 'jp', dialCode: '81' },
    { name: 'Jersey', abbrev: 'je', dialCode: '44' },
    { name: 'Jordan (‫الأردن‬‎)', abbrev: 'jo', dialCode: '962' },
    { name: 'Kazakhstan (Казахстан)', abbrev: 'kz', dialCode: '7' },
    { name: 'Kenya', abbrev: 'ke', dialCode: '254' },
    { name: 'Kiribati', abbrev: 'ki', dialCode: '686' },
    { name: 'Kosovo', abbrev: 'xk', dialCode: '383' },
    { name: 'Kuwait (‫الكويت‬‎)', abbrev: 'kw', dialCode: '965' },
    { name: 'Kyrgyzstan (Кыргызстан)', abbrev: 'kg', dialCode: '996' },
    { name: 'Laos (ລາວ)', abbrev: 'la', dialCode: '856' },
    { name: 'Latvia (Latvija)', abbrev: 'lv', dialCode: '371' },
    { name: 'Lebanon (‫لبنان‬‎)', abbrev: 'lb', dialCode: '961' },
    { name: 'Lesotho', abbrev: 'ls', dialCode: '266' },
    { name: 'Liberia', abbrev: 'lr', dialCode: '231' },
    { name: 'Libya (‫ليبيا‬‎)', abbrev: 'ly', dialCode: '218' },
    { name: 'Liechtenstein', abbrev: 'li', dialCode: '423' },
    { name: 'Lithuania (Lietuva)', abbrev: 'lt', dialCode: '370' },
    { name: 'Luxembourg', abbrev: 'lu', dialCode: '352' },
    { name: 'Macau (澳門)', abbrev: 'mo', dialCode: '853' },
    {
        name: 'Macedonia (FYROM) (Македонија)',
        abbrev: 'mk',
        dialCode: '389',
    },
    { name: 'Madagascar (Madagasikara)', abbrev: 'mg', dialCode: '261' },
    { name: 'Malawi', abbrev: 'mw', dialCode: '265' },
    { name: 'Malaysia', abbrev: 'my', dialCode: '60' },
    { name: 'Maldives', abbrev: 'mv', dialCode: '960' },
    { name: 'Mali', abbrev: 'ml', dialCode: '223' },
    { name: 'Malta', abbrev: 'mt', dialCode: '356' },
    { name: 'Marshall Islands', abbrev: 'mh', dialCode: '692' },
    { name: 'Martinique', abbrev: 'mq', dialCode: '596' },
    { name: 'Mauritania (‫موريتانيا‬‎)', abbrev: 'mr', dialCode: '222' },
    { name: 'Mauritius (Moris)', abbrev: 'mu', dialCode: '230' },
    { name: 'Mayotte', abbrev: 'yt', dialCode: '262' },
    { name: 'Mexico (México)', abbrev: 'mx', dialCode: '52' },
    { name: 'Micronesia', abbrev: 'fm', dialCode: '691' },
    { name: 'Moldova (Republica Moldova)', abbrev: 'md', dialCode: '373' },
    { name: 'Monaco', abbrev: 'mc', dialCode: '377' },
    { name: 'Mongolia (Монгол)', abbrev: 'mn', dialCode: '976' },
    { name: 'Montenegro (Crna Gora)', abbrev: 'me', dialCode: '382' },
    { name: 'Montserrat', abbrev: 'ms', dialCode: '1' },
    { name: 'Morocco (‫المغرب‬‎)', abbrev: 'ma', dialCode: '212' },
    { name: 'Mozambique (Moçambique)', abbrev: 'mz', dialCode: '258' },
    { name: 'Myanmar (Burma) (မြန်မာ)', abbrev: 'mm', dialCode: '95' },
    { name: 'Namibia (Namibië)', abbrev: 'na', dialCode: '264' },
    { name: 'Nauru', abbrev: 'nr', dialCode: '674' },
    { name: 'Nepal (नेपाल)', abbrev: 'np', dialCode: '977' },
    { name: 'Netherlands (Nederland)', abbrev: 'nl', dialCode: '31' },
    {
        name: 'New Caledonia (Nouvelle-Calédonie)',
        abbrev: 'nc',
        dialCode: '687',
    },
    { name: 'New Zealand', abbrev: 'nz', dialCode: '64' },
    { name: 'Nicaragua', abbrev: 'ni', dialCode: '505' },
    { name: 'Niger (Nijar)', abbrev: 'ne', dialCode: '227' },
    { name: 'Nigeria', abbrev: 'ng', dialCode: '234' },
    { name: 'Niue', abbrev: 'nu', dialCode: '683' },
    { name: 'Norfolk Island', abbrev: 'nf', dialCode: '672' },
    {
        name: 'North Korea (조선 민주주의 인민 공화국)',
        abbrev: 'kp',
        dialCode: '850',
    },
    { name: 'Northern Mariana Islands', abbrev: 'mp', dialCode: '1' },
    { name: 'Norway (Norge)', abbrev: 'no', dialCode: '47' },
    { name: 'Oman (‫عُمان‬‎)', abbrev: 'om', dialCode: '968' },
    { name: 'Pakistan (‫پاکستان‬‎)', abbrev: 'pk', dialCode: '92' },
    { name: 'Palau', abbrev: 'pw', dialCode: '680' },
    { name: 'Palestine (‫فلسطين‬‎)', abbrev: 'ps', dialCode: '970' },
    { name: 'Panama (Panamá)', abbrev: 'pa', dialCode: '507' },
    { name: 'Papua New Guinea', abbrev: 'pg', dialCode: '675' },
    { name: 'Paraguay', abbrev: 'py', dialCode: '595' },
    { name: 'Peru (Perú)', abbrev: 'pe', dialCode: '51' },
    { name: 'Philippines', abbrev: 'ph', dialCode: '63' },
    { name: 'Poland (Polska)', abbrev: 'pl', dialCode: '48' },
    { name: 'Portugal', abbrev: 'pt', dialCode: '351' },
    { name: 'Puerto Rico', abbrev: 'pr', dialCode: '1' },
    { name: 'Qatar (‫قطر‬‎)', abbrev: 'qa', dialCode: '974' },
    { name: 'Réunion (La Réunion)', abbrev: 're', dialCode: '262' },
    { name: 'Romania (România)', abbrev: 'ro', dialCode: '40' },
    { name: 'Russia (Россия)', abbrev: 'ru', dialCode: '7' },
    { name: 'Rwanda', abbrev: 'rw', dialCode: '250' },
    { name: 'Saint Barthélemy', abbrev: 'bl', dialCode: '590' },
    { name: 'Saint Helena', abbrev: 'sh', dialCode: '290' },
    { name: 'Saint Kitts and Nevis', abbrev: 'kn', dialCode: '1' },
    { name: 'Saint Lucia', abbrev: 'lc', dialCode: '1' },
    {
        name: 'Saint Martin (Saint-Martin (partie française))',
        abbrev: 'mf',
        dialCode: '590',
    },
    {
        name: 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)',
        abbrev: 'pm',
        dialCode: '508',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        abbrev: 'vc',
        dialCode: '1',
    },
    { name: 'Samoa', abbrev: 'ws', dialCode: '685' },
    { name: 'San Marino', abbrev: 'sm', dialCode: '378' },
    {
        name: 'São Tomé and Príncipe (São Tomé e Príncipe)',
        abbrev: 'st',
        dialCode: '239',
    },
    {
        name: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
        abbrev: 'sa',
        dialCode: '966',
    },
    { name: 'Senegal (Sénégal)', abbrev: 'sn', dialCode: '221' },
    { name: 'Serbia (Србија)', abbrev: 'rs', dialCode: '381' },
    { name: 'Seychelles', abbrev: 'sc', dialCode: '248' },
    { name: 'Sierra Leone', abbrev: 'sl', dialCode: '232' },
    { name: 'Singapore', abbrev: 'sg', dialCode: '65' },
    { name: 'Sint Maarten', abbrev: 'sx', dialCode: '1' },
    { name: 'Slovakia (Slovensko)', abbrev: 'sk', dialCode: '421' },
    { name: 'Slovenia (Slovenija)', abbrev: 'si', dialCode: '386' },
    { name: 'Solomon Islands', abbrev: 'sb', dialCode: '677' },
    { name: 'Somalia (Soomaaliya)', abbrev: 'so', dialCode: '252' },
    { name: 'South Africa', abbrev: 'za', dialCode: '27' },
    { name: 'South Korea (대한민국)', abbrev: 'kr', dialCode: '82' },
    {
        name: 'South Sudan (‫جنوب السودان‬‎)',
        abbrev: 'ss',
        dialCode: '211',
    },
    { name: 'Spain (España)', abbrev: 'es', dialCode: '34' },
    { name: 'Sri Lanka (ශ්‍රී ලංකාව)', abbrev: 'lk', dialCode: '94' },
    { name: 'Sudan (‫السودان‬‎)', abbrev: 'sd', dialCode: '249' },
    { name: 'Suriname', abbrev: 'sr', dialCode: '597' },
    { name: 'Svalbard and Jan Mayen', abbrev: 'sj', dialCode: '47' },
    { name: 'Sweden (Sverige)', abbrev: 'se', dialCode: '46' },
    { name: 'Switzerland (Schweiz)', abbrev: 'ch', dialCode: '41' },
    { name: 'Syria (‫سوريا‬‎)', abbrev: 'sy', dialCode: '963' },
    { name: 'Taiwan (台灣)', abbrev: 'tw', dialCode: '886' },
    { name: 'Tajikistan', abbrev: 'tj', dialCode: '992' },
    { name: 'Tanzania', abbrev: 'tz', dialCode: '255' },
    { name: 'Thailand (ไทย)', abbrev: 'th', dialCode: '66' },
    { name: 'Timor-Leste', abbrev: 'tl', dialCode: '670' },
    { name: 'Togo', abbrev: 'tg', dialCode: '228' },
    { name: 'Tokelau', abbrev: 'tk', dialCode: '690' },
    { name: 'Tonga', abbrev: 'to', dialCode: '676' },
    { name: 'Trinidad and Tobago', abbrev: 'tt', dialCode: '1' },
    { name: 'Tunisia (‫تونس‬‎)', abbrev: 'tn', dialCode: '216' },
    { name: 'Turkey (Türkiye)', abbrev: 'tr', dialCode: '90' },
    { name: 'Turkmenistan', abbrev: 'tm', dialCode: '993' },
    { name: 'Turks and Caicos Islands', abbrev: 'tc', dialCode: '1' },
    { name: 'Tuvalu', abbrev: 'tv', dialCode: '688' },
    { name: 'U.S. Virgin Islands', abbrev: 'vi', dialCode: '1' },
    { name: 'Uganda', abbrev: 'ug', dialCode: '256' },
    { name: 'Ukraine (Україна)', abbrev: 'ua', dialCode: '380' },
    {
        name: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
        abbrev: 'ae',
        dialCode: '971',
    },
    { name: 'United Kingdom', abbrev: 'gb', dialCode: '44' },
    { name: 'United States', abbrev: 'us', dialCode: '1' },
    { name: 'Uruguay', abbrev: 'uy', dialCode: '598' },
    { name: 'Uzbekistan (Oʻzbekiston)', abbrev: 'uz', dialCode: '998' },
    { name: 'Vanuatu', abbrev: 'vu', dialCode: '678' },
    {
        name: 'Vatican City (Città del Vaticano)',
        abbrev: 'va',
        dialCode: '39',
    },
    { name: 'Venezuela', abbrev: 've', dialCode: '58' },
    { name: 'Vietnam (Việt Nam)', abbrev: 'vn', dialCode: '84' },
    {
        name: 'Wallis and Futuna (Wallis-et-Futuna)',
        abbrev: 'wf',
        dialCode: '681',
    },
    {
        name: 'Western Sahara (‫الصحراء الغربية‬‎)',
        abbrev: 'eh',
        dialCode: '212',
    },
    { name: 'Yemen (‫اليمن‬‎)', abbrev: 'ye', dialCode: '967' },
    { name: 'Zambia', abbrev: 'zm', dialCode: '260' },
    { name: 'Zimbabwe', abbrev: 'zw', dialCode: '263' },
    { name: 'Åland Islands', abbrev: 'ax', dialCode: '358' },
];
